# Generated by Django 5.2.15 on 2026-07-07 10:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.TextField(unique=True)),
                ('category', models.CharField(choices=[('tech', 'Technology & R&D'), ('certs', 'Certifications & Compliance'), ('market', 'Market Traction'), ('future', 'Future Readiness'), ('team', 'Team & Leadership'), ('risk', 'Risk Deductions')], max_length=20)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('numeric', 'Numeric'), ('document', 'Document'), ('qualitative', 'Qualitative')], max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=6)),
                ('max_score', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('extraction_prompt', models.TextField(blank=True, null=True)),
                ('valid_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('valid_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'metrics',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('stage', models.TextField()),
                ('sector', models.TextField()),
                ('website', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile_completeness_pct', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'db_table': 'startups',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ScoreHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('tech', 'Technology & R&D'), ('certs', 'Certifications & Compliance'), ('market', 'Market Traction'), ('future', 'Future Readiness'), ('team', 'Team & Leadership'), ('risk', 'Risk Deductions')], max_length=20)),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weighted_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('populated_metrics', models.IntegerField(default=0)),
                ('total_metrics', models.IntegerField(default=0)),
                ('confidence_breakdown_json', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.TextField(blank=True, null=True)),
                ('startup', models.ForeignKey(db_column='startup_id', on_delete=django.db.models.deletion.CASCADE, to='api.startup')),
            ],
            options={
                'db_table': 'score_history',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.TextField(unique=True)),
                ('password_hash', models.TextField()),
                ('role', models.CharField(choices=[('founder', 'Founder'), ('investor', 'Investor'), ('service', 'Service')], default='founder', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('startup', models.ForeignKey(blank=True, db_column='startup_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.startup')),
            ],
            options={
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.TextField()),
                ('doc_type', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('parsed_text', models.TextField(blank=True, null=True)),
                ('parse_status', models.CharField(choices=[('pending', 'Pending'), ('parsed', 'Parsed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('parse_error', models.TextField(blank=True, null=True)),
                ('parsed_at', models.DateTimeField(blank=True, null=True)),
                ('startup', models.ForeignKey(db_column='startup_id', on_delete=django.db.models.deletion.CASCADE, to='api.startup')),
                ('uploaded_by', models.ForeignKey(blank=True, db_column='uploaded_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'documents',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('tech', 'Technology & R&D'), ('certs', 'Certifications & Compliance'), ('market', 'Market Traction'), ('future', 'Future Readiness'), ('team', 'Team & Leadership'), ('risk', 'Risk Deductions')], max_length=20)),
                ('raw_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('weighted_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('populated_metrics', models.IntegerField(default=0)),
                ('total_metrics', models.IntegerField(default=0)),
                ('confidence_breakdown_json', models.JSONField(default=dict)),
                ('computed_at', models.DateTimeField(auto_now_add=True)),
                ('startup', models.ForeignKey(db_column='startup_id', on_delete=django.db.models.deletion.CASCADE, to='api.startup')),
            ],
            options={
                'db_table': 'scores',
                'managed': True,
                'unique_together': {('startup', 'category')},
            },
        ),
        migrations.CreateModel(
            name='MetricValue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.TextField(blank=True, null=True)),
                ('score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('confidence_tag', models.CharField(choices=[('verified_doc', 'Verified Doc'), ('llm_inferred', 'LLM Inferred'), ('self_reported', 'Self Reported')], default='self_reported', max_length=20)),
                ('llm_rationale', models.TextField(blank=True, null=True)),
                ('model_confidence', models.CharField(blank=True, choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], max_length=20, null=True)),
                ('llm_prompt_version', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metric', models.ForeignKey(db_column='metric_id', on_delete=django.db.models.deletion.CASCADE, to='api.metric')),
                ('source_document', models.ForeignKey(blank=True, db_column='source_document_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.document')),
                ('startup', models.ForeignKey(db_column='startup_id', on_delete=django.db.models.deletion.CASCADE, to='api.startup')),
                ('updated_by', models.ForeignKey(blank=True, db_column='updated_by', null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.user')),
            ],
            options={
                'db_table': 'metric_values',
                'managed': True,
                'unique_together': {('startup', 'metric')},
            },
        ),
    ]
