# Generated by Django 5.2.15 on 2026-07-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_document_verification_status_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='startup',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='startup',
            name='onboarding_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
